# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a519773b8bc499b26a633aa95a31c7729cda48fffd6e12b210a681a30e7260fe62b006180d1d3887f050c05a2d68b704daa706e580ddc40f78bc5e96179d5176

test:
  secret_key_base: 4b89936ecbb6e946bee1f342773d8aed81cf35c09cb75ed503757cb96fdafbad2e185564308bdde487f9df3f1d2413e9c3b9d20ac3a40386a2c199299c1610b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
